import { PrivatePageType, PublicPageType } from '@shared/utils/routing';
import { UserRole } from '@prisma/client';

export type RouteLiteral = PrivatePageType | PublicPageType;

export const rolePagesMap: Record<UserRole, RouteLiteral[]> = {
  Client: ['HOME'],
  ClientCorp: ['HOME', 'ORDERS'],
  Driver: ['HOME', 'ORDERS', 'SETTINGS', 'TRANSFERSERVICES'],
  Operator: [
    'ORDERS',
    'ORDEREDIT',
    'ORDERCREATE',
    'TARIFFMANAGEMENT',
    'TARIFFCREATEMANAGEMENT',
    'TARIFFEDITMANAGEMENT',
    'TRANSFERSERVICES',
    'TRANSFERSERVICESDETAIL',
    'TRANSFERSERVICESCREATE',
    'TRANSFERSERVICESEDIT',
    'DRIVERS',
    'USERS',
    'USERSDETAIL',
    'USERSCREATE',
    'USERSEDIT',
    'MAP',
  ],
  Admin: [
    'ORDERS',
    'ORDEREDIT',
    'ORDERCREATE',
    'TARIFFMANAGEMENT',
    'TARIFFCREATEMANAGEMENT',
    'TARIFFEDITMANAGEMENT',
    'TRANSFERSERVICES',
    'TRANSFERSERVICESDETAIL',
    'TRANSFERSERVICESCREATE',
    'TRANSFERSERVICESEDIT',
    'DRIVERS',
    'USERS',
    'USERSDETAIL',
    'USERSCREATE',
    'USERSEDIT',
    'MAP',
    'REFERENCEBOOK',
    'REFERENCEBOOKADDITIONALSERVICES',
    'REFERENCEBOOKPOINTS',
  ],
  None: ['LOGIN', 'REGISTER'],
};
