version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6380:6379'
    environment:
      - NODE_ENV=production
    env_file:
      - ./apps/next-app/.env.production
    networks:
      - app-network
    restart: always

volumes:
  www-html:

networks:
  app-network:
    driver: bridge
