services:
  nextjs:
    image: node:20-alpine3.19
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3008:3008'
    env_file:
      - ./apps/next-app/.env.production
    command: >
      sh -c "yarn prod"
    networks:
      - app-network

volumes:
  www-html:

networks:
  app-network:
    driver: bridge
