services:
  postgresql-db-compass:
    image: postgres:16.2
    environment:
      - NODE_ENV=production
    env_file:
      - ./apps/next-app/.env.production
    volumes:
      - ./persistentdata/db:/var/lib/postgresql/data
      - ./persistentdata/backups:/backups
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - '5434:5432'
    restart: always
    networks:
      - app-network

volumes:
  www-html:

networks:
  app-network:
    driver: bridge
