version: '3.8'

services:
  web:
    build:
      context: .
    container_name: web
    command: ["yarn", "bullmq"]
    depends_on:
      - redis
    networks:
      - app-network
    ports:
      - "3001:3001"
    environment:
      - ./apps/next-app/.env.production
    restart: always

networks:
  app-network:
    driver: bridge
