version: '3.8'

services:
  worker:
    image: node:20-alpine3.19
    container_name: worker
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=production
    command: sh -c "yarn worker"
    networks:
      - app-network
    restart: always
    ports:
      - "3001:3001"
      - "4000:4000"
      - "6379:6379"

volumes:
  www-html:

networks:
  app-network:
    driver: bridge
