version: '3.8'

services:
  prisma-studio:
    image: node:20-alpine3.19
    container_name: prisma-studio
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    env_file:
      - ./apps/next-app/.env.production
    command: sh -c "yarn worker"
    networks:
      - app-network
    restart: always

volumes:
  www-html:

networks:
  app-network:
    driver: bridge
