services:
  worker:
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - ./apps/next-app/.env.production
    command: >
      sh -c "yarn worker"
    networks:
      - app-network
    restart: always

volumes:
  www-html:

networks:
  app-network:
    driver: bridge
