services:
  worker:
    build:
      context: .
    container_name: worker
    depends_on:
      - redis
    environment:
      - ./apps/next-app/.env.production
    command: >
      sh -c "yarn worker"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
