services:
  bullmq:
    image: node:20-alpine3.19
    container_name: bullmq
    networks:
      - app-network
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    env_file:
      - ../apps/next-app/.env.production
    command: >
      sh -c "yarn bullmq"
    restart: always

volumes:
  www-html:

networks:
  app-network:
    driver: bridge
