import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { SelectSingle, TextInput } from '@shared/components/ui/inputs';
import { vehicleTypeOptions } from '@shared/lib/effector/vehicles/optionsTranslation/optionsTranslationVehicle';
import { Controller, useFormContext } from 'react-hook-form';
const TariffEditStep1 = () => {
    const { control } = useFormContext();
    return (_jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 sm:grid-cols-2 lg:grid-cols-2 gap-4", children: [_jsx("div", { className: "form-group", children: _jsx(Controller, { name: "name", control: control, rules: { required: 'Tariff name is required' }, render: ({ field }) => (_jsx(TextInput, { ...field, placeholder: "Enter tariff name", label: "Tariff Name" })) }) }), _jsx("div", { className: "form-group", children: _jsx(Controller, { name: "vehicleType", control: control, rules: { required: 'Vehicle type is required' }, render: ({ field }) => (_jsx(SelectSingle, { label: "Vehicle Type", classNameLabel: "block text-4 font-medium text-gray-500 mb-2", ...field, options: vehicleTypeOptions, value: vehicleTypeOptions.find((option) => option.value === field.value) || null, onChange: (selectedOption) => field.onChange(selectedOption?.value), placeholder: "Select vehicle type" })) }) }), _jsx("div", { className: "form-group", children: _jsx(Controller, { name: "description", control: control, render: ({ field }) => (_jsx(TextInput, { ...field, placeholder: "Enter description", label: "Description", value: field.value ?? '' })) }) }), _jsx("div", { className: "form-group", children: _jsx(Controller, { name: "price", control: control, render: ({ field }) => (_jsx(TextInput, { ...field, placeholder: "price", label: "Price", value: field.value, type: "number" })) }) })] }));
};
export default TariffEditStep1;
