'use client';
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useOrderCreateLogic } from '@features/orders/create/OrderCreate.logic';
import DriversNearby from '@widgets/drivers-nearby/ui/DriversNearby';
import MapDriver from '@widgets/map/ui/MapDriver';
import OrderStartEndSelector from '@widgets/orders/order-route/OrderRouteSelector';
import FilterTariff from '@widgets/filter-tariff/FilterTariff';
import OrderCreateWidget from '@widgets/order-create-widget/OrderCreateWidget';
import { FormProvider } from 'react-hook-form';
import ClientSelector from '@widgets/clients-orders/ClientSelector';
import IntermediatePoints from '@widgets/intermediate-points/IntermediatePoints';
import AdditionalServices from '@widgets/orders/additional-services/AdditionalServices';
import WaitingTimeControl from '@widgets/orders/waiting-time-control/WaitingTimeControl';
import HeaderOrder from '@widgets/orders/header-order/HeaderOrder';
import CalendarOrder from '@widgets/orders/calendar-order/CalendarOrder';
const OrderCreateView = ({ uuid }) => {
    const formMethods = useOrderCreateLogic(uuid);
    return (_jsx(FormProvider, { ...formMethods, children: _jsxs("div", { className: 'flex flex-col gap-4', children: [_jsx(HeaderOrder, { uuid: uuid }), _jsxs("div", { className: 'flex flex-col gap-8', children: [_jsxs("div", { className: "w-full h-[660px] flex flex-row gap-4", children: [_jsx("div", { className: "hidden lg:flex flex-1 flex-shrink-0 basis-[calc(65%-1.5rem)] h-auto bg-white rounded-xl border", children: _jsx(MapDriver, { ...formMethods }) }), _jsx("div", { className: "flex-1 flex-shrink-0 basis-[calc(35%-1.5rem)] h-auto flex flex-col justify-between gap-4", children: _jsx(DriversNearby, { ...formMethods, page: formMethods.page ? Number(formMethods.page) : 1, perPage: formMethods.perPage ? Number(formMethods.perPage) : 10, handlePageChange: (newPage) => formMethods.setValue('page', newPage) }) })] }), _jsxs("div", { className: 'flex flex-row gap-4', children: [_jsxs("div", { className: 'w-full flex bg-white flex-col gap-8 p-4 rounded-md', children: [_jsx("div", { className: 'w-full flex flex-col rounded-md', children: _jsx(OrderStartEndSelector, { ...formMethods }) }), _jsx("div", { className: 'w-full flex flex-1 flex-col rounded-md', children: _jsx(ClientSelector, { ...formMethods }) })] }), _jsx("div", { className: 'w-full flex flex-col bg-white rounded-md', children: _jsx(CalendarOrder, {}) })] }), _jsxs("div", { className: 'w-full flex flex-row gap-4', children: [_jsx("div", { className: "w-full flex bg-white flex-col gap-8 p-4 rounded-md", children: _jsxs("div", { className: 'flex flex-row gap-4 bg-white rounded-xl', children: [_jsxs("div", { className: 'w-full flex flex-col gap-4', children: [_jsx(AdditionalServices, { ...formMethods }), _jsx(WaitingTimeControl, { ...formMethods })] }), _jsx(IntermediatePoints, { ...formMethods })] }) }), _jsx(FilterTariff, { ...formMethods })] }), _jsx(OrderCreateWidget, { ...formMethods })] })] }) }));
};
export default OrderCreateView;
