import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
export const vehicleColumns = [
    {
        accessor: 'number',
        header: '№',
        sortable: false,
        className: 'w-[100px] text-center',
    },
    {
        accessor: 'vehicleInfo',
        header: 'Vehicle Info',
        render: (row) => (_jsxs("span", { className: "text-gray-800", children: [row.vehicleInfo?.vehicleType, " - ", row.vehicleInfo?.serviceLevels] })),
        sortable: true,
        className: 'w-[200px]',
    },
    {
        accessor: 'brand',
        header: 'Brand',
        render: (row) => _jsx("span", { className: "text-gray-800", children: row.brand }),
        sortable: true,
        className: 'w-[150px]',
    },
    {
        accessor: 'model',
        header: 'Model',
        render: (row) => _jsx("span", { className: "text-gray-800", children: row.model }),
        sortable: true,
        className: 'w-[150px]',
    },
    {
        accessor: 'year',
        header: 'Year',
        render: (row) => _jsx("span", { className: "text-gray-800", children: row.year }),
        sortable: true,
        className: 'w-[150px]',
    },
    {
        accessor: 'color',
        header: 'Color',
        render: (row) => _jsx("span", { className: "text-gray-800", children: row.color }),
        sortable: true,
        className: 'w-[150px]',
    },
    {
        accessor: 'plateNumber',
        header: 'Plate Number',
        render: (row) => _jsx("span", { className: "text-gray-800", children: row.plateNumber }),
        sortable: true,
        className: 'w-[150px]',
    },
    {
        accessor: 'isAvailable',
        header: 'Available',
        render: (row) => (_jsx("span", { className: `px-2 py-1 rounded ${row.isAvailable ? 'bg-green-200 text-green-800' : 'bg-red-200 text-red-800'}`, children: row.isAvailable })),
        sortable: true,
        className: 'flex-grow',
    },
    {
        accessor: 'actions',
        header: 'Actions',
        render: (row) => row.actions,
        sortable: false,
        className: 'w-[200px]',
    },
];
